### ISSUE TITLE
Scrum updates: Week-3 (Jun 06, 2020)

### ISSUE THREAD

**Issue by povel62** [povel62/cpsc455-project#10]

**Comment by povel62** [comment]
For this week I worked on creating issues, discussing requirements with the team and working on implementation for signup. Creating models and appropriate apis. Also, discussed further requirements and added issues on github. 
Reviewed code and helped team members with any issues.

**Comment by aid848** [comment]
During this cycle, I worked on the user model (with the guest mode), the secure storage of Kaggle API keys and password hashes, I also discussed with my team the features of the login process and the required data we would need. I plan to continue working on the backend features and integrate with both the Kaggle and BlackBox ml endpoints to implement more functionality.  I don't think we have run into any major issues so far.

**Comment by bisht10** [comment]
(1) what you’ve worked on in the previous two weeks,
- worked on setting up the signup, login front end with react-redux, and imported material UI tabs for styling purposes
 (2) what you’ll be working on in the next two weeks 
 - frontend for the control dashboard and adding collaborators to a job
 (3) where you might have gotten stuck during the last two weeks.
 - learning to redux took a while

**Comment by srahul14** [comment]
(1) what you’ve worked on in the previous two weeks:  worked on developing the frontend for our system. Worked on setting up the login, signup and file upload functionalities.
(2) what you’ll be working on in the next two weeks: frontend for the control dashboard and adding collaborators to a job
(3) where you might have gotten stuck during the last two weeks: learning and using redux to integrate into our system
