### ISSUE TITLE
Scrum updates: Week-4 (Jun 13, 2020)

### ISSUE THREAD

**Issue by povel62** [povel62/cpsc455-project#28]

**Comment by aid848** [comment]
I worked on building the Kaggle account dashboard frontend that used the Kaggle API and our own backend routes to facilitate integrating Kaggle data/competitions with the autoML system. Some major issues I ran into were that the Kaggle API for competitions seemed to change how competitions were accessed midway through development and I had to proxy downloads through our back end to avoid CORS problems. I plan on working on bridging file transfers between Kaggle and Ensamble^2 and refining the Kaggle dashboard workflow.

**Comment by povel62** [comment]
This sprint I worked on creating the job model and the respective apis.
Also, worked on revamping the ui with more styling and validation

**Comment by bisht10** [comment]
(1) what you’ve worked on in the previous two weeks,
-> worked on building the frontend for control dashboard and my-account page and making necessary backend endpoint changes
(2) what you’ll be working on in the next two weeks
-> making the flow between components smooth, styling and incorporating share functionality
(3) where you might have gotten stuck during the last two weeks.
->  not having access to emsemble2 through ssh slowed down the whole team

**Comment by srahul14** [comment]
(1) what you’ve worked on in the previous two weeks,
-> worked on developing the frontend for the tutorial and account page. Added and optimized edit functionality for users in the frontend, middleware and backend. 
(2) what you’ll be working on in the next two weeks
-> I will be working on integrating the remaining functionalities including Ensemble^2 integration into the frontend. I will also be optimizing the system to be more user-friendly by tweaking the workflow. I also plan on working on integrating and adding some extra functionalities to our system. 
(3) where you might have gotten stuck during the last two weeks.
-> not having complete access to emsemble2 slowed down the whole team. Once the interaction with Emsemble^2 is sorted, the workflow can then be tweaked as needed to enhance our system.
