### ISSUE TITLE
Scrum updates: Week-2 (May 30, 2020)

### ISSUE THREAD

**Issue by srahul14** [povel62/cpsc455-project#3]

**Comment by aid848** [comment]
I worked on brainstorming and completing project progress 1 requirements with my team for an auction lottery website with my team. After getting accepted to do the Blackboxml project I helped redo the requirements and sketches to match the new project. Our main challenge was the change of project direction but we are catching up quickly and are excited to work on it. For this coming iteration, I plan to begin working on the minimal requirements (to be divided up) and consulting with the Blackboxml team for more information regarding the system and the backend features and specifics.

**Comment by srahul14** [comment]
I also worked on brainstorming and completing project progress 1 requirements with my team for an auction lottery website with my team. After getting accepted to do the Blackboxml project I also helped redo the requirements and sketches to match the needs and requirements of the new project. For the coming iteration, I would working with the team to divide and assign the minimal required tasks for the BlackboxML project in order to finish them asap.

**Comment by povel62** [comment]
For workshop 1 progress, we divided and brainstormed issues and features for an online lottery/auction system which can viewed under the readme file. We are also registered now into the automl project, for which we are re-doing the work and brainstorming. Talked with Ali for certain feature implementations in new web app for autoML.

**Comment by bisht10** [comment]
What did you work on this past iteration?
- brainstorming use cases and creating a rough UI sketch for the autoML project as well as our old lottery/auction website
What were any major issues/challenges you ran into?
-changing project from the auction website to autoML project
What do you plan to work on for this coming iteration?
-get started on minimal requirements for the autoML project
